#./Lab2
CC = gcc
CFLAGS = -I -g

lab3: lab3.c
	$(CC) $(CFLAGS) -o Lab3 lab3.c ContextSwitch.c FileParser.c FirstComeFirstServe.c Process.c ProcessDynamicArray.c ProcessLinkedList.c ProcessMinHeap.c ProcessResult.c ProcessResultsDynamicArray.c RoundRobin.c ShortestJobFirst.c -g

.PHONY: clean

clean:
	rm -f Lab3

